development: &development
  host: localhost
  port: 8000
  protocol: stomp
  stomp_host: localhost
  stomp_port: 61613
  reactor: select
  morbidq: 0
  restrict_access: 0
 
test:
  <<: *development
 
production:
  host: 207.192.69.147
  port: 8000
  protocol: stomp
  stomp_host: 207.192.69.147
  stomp_port: 61613
  reactor: epoll
  morbidq: 0
  restrict_access: 1